### ISSUE TITLE
Decide Arch ᕦ( ͡° ͜ʖ ͡°)ᕤ

### ISSUE THREAD

**Issue by worker8** [worker8/newp#2]
MVPVM thing ⚔️ redux kinda thing

@worker8 needs some training for redux kinda thing if it's chosen

but C++ is a little overkill 🤕 😝

**Comment by kittinunf** [comment]
Well if you aim to support iOS too, you do not have many choices ...

**Comment by worker8** [comment]
not targetting iOS, so... Redux+Kotlin? ✨

**Comment by worker8** [comment]
redux decided 👍
